---
- name: ssh-port changing
  hosts: all
  #gather_facts: no
  remote_user: root
  tasks:
  - name: Setup alternate SSH port
    lineinfile:
      dest: "/etc/ssh/sshd_config"
      regexp: "^Port"
      line: "Port 8875"
   # notify: "Restart sshd"

  - name: Setup selinux for alternate SSH port
    seport:
      ports: "8875"
      proto: "tcp"
      setype: "ssh_port_t"
      state: "present"

  - name: Restart sshd
    service:
      name: sshd
      state: restarted

  - name: install firewalld
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
    package:
      name: firewalld
      state: latest

  - name: start firewall
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
    systemd:
      name: firewalld
      state: started

  - name: Open port 8875
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
    command: "firewall-cmd --zone=public --add-port=8875/tcp --permanent"